mariadb:
  architecture: 'standalone'
  image:
    registry: 'docker.io'
    repository: 'bitnamilegacy/mariadb'
    tag: '10.6.8-debian-11-r9'
  auth:
    database: 'golist'
    username: 'golist'
    password: 'golist'
