auth:
    password: ENC[AES256_GCM,data:JEBUQHbx7dSPl8RacWWduQ==,iv:OprsDin3CToYv3m6dP1JqwlL4/c8zviLkgI/ihkA/lw=,tag:Jzfb0+FOcFqrqAxRRKQllA==,type:str]
sops:
    age:
        - recipient: age1jclhxz7d3faza8dzjfrxzhxvhsgvw4u2jp56dwkx2w07hzcxepvsasd2j0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQkRhMXE4RytSMjRGOXI4
            Z0ZubllMZVRKT0p3N04xUUJFdndBOHdMMVdrCmRvbXM2OGxncklZekM5dmhIOFQ3
            RENCQkRUNEZFRnYxbitxeGxjYlFERzgKLS0tIDFuNUNxOFZLUjJwM3lRL0xJRzNm
            REVtV0JxanBrSFZnWVdHSk9wVlBlbk0KAFdfQSgKbPwUxl4FqR7itJIYzRXEJVw1
            39Ae8wMMyxCFaHp8dSXLBLUeQh46Dn8afQBeLNqOYTtbFkfznehVhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:23:17Z"
    mac: ENC[AES256_GCM,data:X8Qhz3IUI8ZYyvDHl5I5ET3b6WgA9ieYIqWCOMbTm6nqrpLtl3foK1c2BxJcYgOVgFVatNAsQOdtYdt43GoqBR9dtFZGOp64jazfeSef4SMPzC95Y/TiUgMDKEAiUzcdCja5AQo2sWNmAkeA4vkp6w2NFEuB12sYTiqpcG0JFvE=,iv:AgWiQDFKmW86JxtVmt85FgwBlAJnaIJTjASBY0yeNq8=,tag:yBhrq0CvRwHCWLEdOKCOOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
