auth:
    password: ENC[AES256_GCM,data:EGyDL0o46eUYHTuGHg==,iv:QJdQ5li+IIdD1he4lY4V36EmfQUrPBA7aJijE4vPxcg=,tag:AxrJBXxHvkHsy4zRqejH5w==,type:str]
sops:
    age:
        - recipient: age1jclhxz7d3faza8dzjfrxzhxvhsgvw4u2jp56dwkx2w07hzcxepvsasd2j0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMzdES0tkdExhbmxEVWZM
            S1VkQVZGeTA4ZFE1YndXZThtaU8rUk9Lb3pNCllaWmVyaVBqV0xwMTMyZ3M2QVI5
            bzk5eTI1dy80cWJ6NWY1WlhiKzZSaHcKLS0tIG9VK2JRcHAxQ0g0OWZjNDZMUklK
            Q2J3U09qY05uVGVwWUhkZ0lGcUNnR0UKcAXsbjwC6xzEYxTls5sv/U5/HrfTsvLZ
            S/m+ltdaIwRpsZf4HV9v2dBwfXUGCW/jZc3zgU87sMPe44UKkyeWzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:23:37Z"
    mac: ENC[AES256_GCM,data:3h2hHqDVFbdmaoTqHIpiITt2DkDl6Ag4Qwp7/sZJX/FQ6FCm5+AmBMzbuvfhzn+kLkMNU7Po3RuDCOvU8A3F3EQZxbVdc5QqmOR4RpX+PmRXbjW3T7zoB1CMdTFowjIv39nFibkOaU/vMGlxwkUFmVKnsM353mbZkB/mynyzeKs=,iv:Dq4/Gb+jwANZu39J6kuBDuDi8LCLeBuf48tlXed8KqA=,tag:u9NkJIp1oUI7pUU8F6h4Dw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
