auth:
    password: ENC[AES256_GCM,data:ESu4aZpd+euYLPq3,iv:wl+ETNgb6QBr7WFJ/4hMmaYbSrrYYXPtR6gH4ogPqig=,tag:UYLD1xd2RGOwgr1nsmuwNQ==,type:str]
sops:
    age:
        - recipient: age1jclhxz7d3faza8dzjfrxzhxvhsgvw4u2jp56dwkx2w07hzcxepvsasd2j0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2I5OXM1ZVVGMERzUzRh
            S29MMFhmYm1ETkdQR0tLYXVZTkIwTUpRd2xrCkNoT0oxNkM2M1FWUm9rczNYb1Zt
            SG0xTWk0ZVkrL2lQd0M2dnpZckJpQjgKLS0tIDhwdGQ0c2RERXR6aG0zc2VyemZj
            UWZuMnE0ckdQeW9QdFc2RkVIVHNhTDgKbZ2ND72NodRejCBRLjDFSQtE3u/qCV7M
            IxR0cILezOLL7OyleOuUBHscMCjO2I3xwu8zabMOLrP6s8OReic7ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:22:46Z"
    mac: ENC[AES256_GCM,data:tA+1xWs08ZLr5Zrf1658awIDk2s62eDOH1f6b0JXZgeMtzXqFt7Gzd3gGnzRDjbBfpC/B9h/qzD9tALcawY1qV7d1IVH32Qchsl5S6XmrBW3uUHn9BcnzhXQhsFKMFTPKp0pP64UfkJHezxGggRJdwEOorJjCu1Sqh3l5nQmkck=,iv:sR8geZhdHwEjRgn8Isj6ZYqLGwYColT6ztKLiIUTuHk=,tag:QQGJF+cReskRu+ugsDG39g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
